reviewer/urls.py
from django.urls import path
from reviewer.views.product import ProductCreateView, ProductDetail, ProductDeleteView, ProductUpdateView, \
    ProductListView
from reviewer.views.review import ReviewCreateView, ReviewUpdateView, ReviewDeleteView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/', ProductDetail.as_view(), name='product_detail'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/add_review/', ReviewCreateView.as_view(), name='review_create'),
    path('review/<int:pk>/update/', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
]

source/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reviewer.urls')),
    path('auth/', include('accounts.urls')),
]

reviewer/models.py
from django.db import models
from source import settings


class Product(models.Model):
    CATEGORY_CHOICES = (
        ('CPU', 'Processor'),
        ('GPU', 'Graphics Card'),
        ('MONITOR', 'Monitor'),
        ('MOTHERBOARD', 'Motherboard'),
    )

    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Name')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=50, verbose_name='Category')
    description = models.TextField(max_length=3000, blank=True, null=True, verbose_name='Description')
    image = models.URLField(null=True, blank=True, verbose_name='Image URL')

    def __str__(self):
        return self.name

    def average_rating(self):
        total_reviews = self.reviews.count()
        if total_reviews > 0:
            total_rating = sum([review.rating for review in self.reviews.all()])
            return round(total_rating / total_reviews, 1)
        return None


class Review(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='reviews',
        verbose_name='Author'
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='reviews',
        verbose_name='Product'
    )
    feedback = models.TextField(
        max_length=3000,
        blank=False,
        null=False,
        verbose_name='Feedback'
    )
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])

    def __str__(self):
        return f"{self.author.username}'s review of {self.product.name}"

reviewer/forms.py
from django import forms
from reviewer.models import Product, Review


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'category', 'description', 'image')


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('feedback', 'rating')

reviewer/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView

from reviewer.forms import ProductForm
from reviewer.models import Product


class IndexView(ListView):
    template_name = 'index.html'
    model = Product
    context_object_name = 'products'
    paginate_by = 8


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product_create.html'
    success_url = reverse_lazy('index')


class ProductDetail(DetailView):
    template_name = 'product_detail.html'
    model = Product


class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'category', 'description', 'image']
    template_name = 'product_update.html'
    success_url = reverse_lazy('index')


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'product_delete.html'
    success_url = reverse_lazy('inde')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(pk=self.kwargs['pk'])

reviewer/views/product.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from reviewer.forms import ProductForm
from reviewer.models import Product


class ModeratorRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.groups.filter(name='Moderators').exists()


class ProductListView(ListView):
    template_name = 'index.html'
    model = Product
    context_object_name = 'products'
    paginate_by = 8


class ProductCreateView(ModeratorRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product_create.html'
    success_url = reverse_lazy('index')


class ProductDetail(DetailView):
    template_name = 'product_detail.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.object
        reviews_list = product.reviews.all()
        paginator = Paginator(reviews_list, 3)

        page = self.request.GET.get('page')
        reviews = paginator.get_page(page)

        context['reviews'] = reviews
        return context


class ProductUpdateView(ModeratorRequiredMixin, UpdateView):
    model = Product
    fields = ['name', 'category', 'description', 'image']
    template_name = 'product_update.html'
    success_url = reverse_lazy('index')


class ProductDeleteView(ModeratorRequiredMixin, DeleteView):
    model = Product
    template_name = 'product_delete.html'
    success_url = reverse_lazy('inde')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(pk=self.kwargs['pk'])

reviewer/views/review.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from reviewer.models import Review, Product
from reviewer.forms import ReviewForm


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    form_class = ReviewForm
    template_name = 'review_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.product = Product.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)

    def get_initial(self):
        initial_data = super().get_initial()
        initial_data['author'] = self.request.user
        initial_data['product'] = Product.objects.get(pk=self.kwargs['pk'])
        return initial_data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = Product.objects.get(pk=self.kwargs['pk'])
        return context

    def get_success_url(self):
        return reverse_lazy('product_detail', kwargs={'pk': self.kwargs['pk']})


class ReviewUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Review
    form_class = ReviewForm
    template_name = 'review_update.html'

    def get_success_url(self):
        return reverse_lazy('product_detail', kwargs={'pk': self.object.product.pk})

    def test_func(self):
        review = self.get_object()
        return self.request.user == review.author or self.request.user.groups.filter(name='Moderators').exists()


class ReviewDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Review
    template_name = 'review_delete.html'

    def get_success_url(self):
        return reverse_lazy('product_detail', kwargs={'pk': self.object.product.pk})

    def test_func(self):
        review = self.get_object()
        return self.request.user == review.author or self.request.user.groups.filter(name='Moderators').exists()

reviewer/templates/base.html
{% load bootstrap5 %}
{% load reviewer_extras %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if request.user|has_group:"Moderators" %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'product_create' %}">Add</a>
                </li>
                {% endif %}
                {% block menu %}
                {% endblock %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'current_user_profile' %}"><button type="button" class="btn btn-success">{{ user.username }}</button></a>
                </li>
                <li class="nav-item">
                    <form action="{% url 'logout' %}" method="post" class="form-inline">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" value="Logout">
                    </form>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'login' %}" class="btn btn-primary">Log in</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'register' %}" class="btn btn-success">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container py-4">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

reviewer/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="row">
    {% for product in products %}
    {% include 'partial/product_list.html' with products=products %}
    {% endfor %}
</div>
{% if is_paginated %}
{% include 'partial/pagination.html' %}
{% endif %}
{% endblock %}

reviewer/templates/product_create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}Create Product{% endblock %}

{% block content %}
  <h1>Create Product</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Create</button>
  </form>
{% endblock %}

reviewer/templates/product_delete.html
{% extends 'base.html' %}

{% block title %}Delete Product{% endblock %}

{% block content %}
  <h1>Delete Product</h1>
  <p>Are you sure you want to delete "{{ product.name }}" and all its associated reviews?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

reviewer/templates/product_detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load reviewer_extras %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% block title %}
View Product
{% endblock %}
{% block menu %}
{% if request.user|has_group:"Moderators" %}
<li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'product_update' product.pk %}">Edit</a>
</li>
<li>
    <a class="nav-link active" aria-current="page" href="{% url 'product_delete' product.pk %}">Delete</a>
</li>
{% endif %}
{% endblock %}
<div class="container">
    {% block content %}
    <h2 style="margin-top: 1.5rem">{{ product.name }}</h2>
    <div class="card">
        <div class="row no-gutters">
            <div class="col-md-4">
                {% if product.image %}
                <img src="{{ product.image }}" class="card-img">
                {% else %}
                <img src="https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg?20200913095930"
                     class="card-img">
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <p class="card-text"><b>Description:</b> {{ product.description }}</p>
                    <h6 class="card-title"><b>Category:</b> {{ product.get_category_display }}</h6>
                </div>
            </div>
        </div>
    </div>

    <h3 style="margin-top: 2rem">Reviews {% if request.user.is_authenticated %}<a href="{% url 'review_create' pk=product.pk %}" class="btn btn-outline-primary me-2">Add Review</a>{% endif %}</h3>
    <p>Average Rating: {% if product.average_rating %}{{ product.average_rating }}{% else %}N/A{% endif %}</p>
    {% if reviews %}
    {% for review in reviews %}
    <div class="card" style="margin-bottom: 1rem">
        <div class="card-body">
            <h5 class="card-title"><a href="{% url 'user_profile' review.author.id %}">{{ review.author.username }}</a> ({{ review.author.email }}) - {{ review.rating }}</h5>
            <p class="card-text">{{ review.feedback }}</p>
            {% if request.user == review.author or request.user|has_group:"Moderators" %}
            <a href="{% url 'review_update' pk=review.pk %}">Edit</a> |
            <a href="{% url 'review_delete' pk=review.pk %}">Delete</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No reviews for this product yet.</p>
    {% endif %}
    <div class="pagination">
        <span class="step-links">
            {% if reviews.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ reviews.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ reviews.number }} of {{ reviews.paginator.num_pages }}.
            </span>

            {% if reviews.has_next %}
                <a href="?page={{ reviews.next_page_number }}">next</a>
                <a href="?page={{ reviews.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endblock %}
</div>

reviewer/templates/product_update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}Update Product{% endblock %}

{% block content %}
  <h1>Update Product</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Update</button>
    <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

reviewer/templates/review_create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    <h2>Add Review for {{ product.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">Post</button>
    </form>
{% endblock %}

reviewer/templates/review_delete.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    <h2>Delete Review for {{ object.product.name }}</h2>
    <p>Are you sure you want to delete this review?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete this review</button>
    </form>
    <a href="{% url 'product_detail' pk=object.product.pk %}">Cancel</a>
{% endblock %}

reviewer/templates/review_update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    <h2>Update Review for {{ object.product.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">Update Review</button>
    </form>
{% endblock %}